name: Dakara
on:
  # schedule:
  #   - cron: "8 0 * * *"
  #   - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  dakara:
    name: "Daka Ra"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [16.x]
    env:
      COMPANY_CODE: ${{ secrets.COMPANY_CODE }}
      EMPLOYEE_CODE: ${{ secrets.EMPLOYEE_CODE }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Steup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Punch 1
        if: github.event.schedule == '8 0 * * *'
        run: pnpm start up
      - name: Punch 2
        if: github.event.schedule == '0 11 * * *'
        run: pnpm start down
